---
- name: Configure Azure NSG
  hosts: localhost

  tasks:
    - name: Get facts for all subscriptions, including ones that are disabled.
      azure.azcollection.azure_rm_subscription_info:
        all: true

    - name: Discover all Azure NSG's in a subscription
      azure.azcollection.azure_rm_securitygroup_info:
        resource_group: "{{ nsg_config.rg }}"
      register: azure_nsg_list

    - name: Print list
      ansible.builtin.debug:
        var: azure_nsg_list

    - name: Ensure Azure NSG exists
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ nsg_config.rg }}"
        name: "{{ nsg_config.name }}"
        tags:
          ansible: managed
        purge_rules: true
        rules: "{{ nsg_config.rules }}"