---
- name: Configure Azure NSG
  hosts: localhost

  tasks:
    - name: Get facts for all subscriptions, including ones that are disabled.
      azure.azcollection.azure_rm_subscription_info:
        all: true
      register: az_subscription

    - name: Gather VM info from Azure
      azure.azcollection.azure_rm_virtualmachine_info:
        resource_group: "{{ nsg_config.rg }}"
      register: vm_facts

    - name: Gather VM sizes
      azure.azcollection.azure_rm_virtualmachinesize_info:
        location: "eastus"
      register: vm_size_facts

    # - name: Discover all RG's in a subscription
    #   azure.azcollection.azure_rm_resourcegroup_info:
    #     subscription_id: "{{ item }}"
    #   loop: "{{ az_subscription }}"
    #   async: 0
    #   timeout: 600
    #   register: rg_lookup_result

    # - name: Wait for previous step to complete
    #   ansible.builtin.async_status:
    #     jid: "{{ item.ansible_job_id }}"
    #   loop: "{{ rg_lookup_result.results }}"
    #   register: job_result
    #   until: job_result.finished
    #   retries: 300

    - name: Discover all Azure NSG's in a subscription
      azure.azcollection.azure_rm_securitygroup_info:
        resource_group: "{{ nsg_config.rg }}"
      register: azure_nsg_list

    - name: Print list
      ansible.builtin.debug:
        var: azure_nsg_list

    - name: Ensure Azure NSG exists
      azure.azcollection.azure_rm_securitygroup:
        resource_group: "{{ nsg_config.rg }}"
        name: "{{ nsg_config.name }}"
        tags:
          ansible: managed
        purge_rules: true
        rules: "{{ nsg_config.rules }}"
