---
- name: Provision resource group in Azure
  hosts: localhost
  gather_facts: false

  # Temporary
  vars:
    resource_group_name: azure_poc_ptoal
    storage_account_name: ptoalpoc
    operating_system: other
    publisher: MicrosoftWindowsServer
    version: latest
    offer: WindowsServer
    azureuser: azadmin
    azurepassword: !vault |
          $ANSIBLE_VAULT;1.2;AES256;rhdemo
          35336464363933383136343062663761653365663936393366636233616166653830303932316165
          3161386333396139313938646666656336626632343534660a393463326333383330353739623862
          37363165393735636361383861633133643335316135396661376439353066356364626636666638
          6335613735343534340a633764343532656435353265303534353562343061643334313539663939
          65366133366239363330623261643266303764616465323465376433376436636263
    sku: 2022-datacenter-azure-edition-core
    vm_size: Standard_B1s
    vm_names: "{{ new_vm_hostname.split(',') }}"
    # vm_names:
    #   - "{{ new_vm_hostname }}"

  tasks:
    - name: Resource Group Creation
      ansible.builtin.include_role:
        name: azure_create_resource_group

    - name: Storage Account Creation
      ansible.builtin.include_role:
        name: azure_create_storage_account

    - name: Provision instance Windows
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ item }}"
        storage_account: "{{ storage_account_name }}"
        admin_username: "{{ azureuser }}"
        admin_password: "{{ azurepassword }}"
        vm_size: "{{ vm_size }}"
        os_type: Windows
        managed_disk_type: Standard_LRS
        open_ports:
          - 22
          - 5985
          - 5986
          - 80
          - 443
        image:
          publisher: "{{ publisher }}"
          offer: "{{ offer }}"
          version: "{{ version }}"
          sku: "{{ sku }}"
        tags:
          ansible: managed
          ansible_connection: "{{ new_vm_connection }}"
      register: azure_vm
      loop: "{{ vm_names }}"
      when: publisher == "MicrosoftWindowsServer"
      async: 300
      poll: 0

    - name: Wait for VM Creation to complete
      ansible.builtin.async_status:
        jid: "{{ item.ansible_job_id }}"
      register: jobs_azure_vm
      retries: 60
      delay: 5
      until: jobs_azure_vm.finished
      loop: "{{ azure_vm.results }}"

    - name: Enable WinRM
      when: publisher == "MicrosoftWindowsServer" and new_vm_connection == "winrm"
      block:
        - name: Create VM script extension to enable HTTPS WinRM listener
          azure.azcollection.azure_rm_virtualmachineextension:
            name: winrm-extension
            resource_group: "{{ resource_group_name }}"
            virtual_machine_name: "{{ item }}"
            publisher: Microsoft.Compute
            virtual_machine_extension_type: CustomScriptExtension
            type_handler_version: "1.9"
            settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible-documentation/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}' # noqa:yaml[line-length]
            auto_upgrade_minor_version: true
          loop: "{{ vm_names }}"

        - name: Loop to verify WinRM
          ansible.builtin.include_tasks: enable_winrm_loop_azure.yml
          loop: "{{ vm_names }}"


    - name: Enable SSH
      when: publisher == "MicrosoftWindowsServer" and new_vm_connection == "ssh"
      block:
        - name: Create VM script extension to enable SSH
          azure.azcollection.azure_rm_virtualmachineextension:
            name: ssh-extension
            resource_group: "{{ resource_group_name }}"
            virtual_machine_name: "{{ item }}"
            publisher: Microsoft.Azure.OpenSSH
            virtual_machine_extension_type: WindowsOpenSSH
            type_handler_version: "3.0"
          loop: "{{ vm_names }}"

        - name: Loop to verify SSH
          ansible.builtin.include_tasks: enable_ssh_loop_azure.yml
          loop: "{{ vm_names }}"
