---
- name: Provision resource group in Azure
  hosts: localhost
  gather_facts: false

  # Temporary
  vars:
    resource_group_name: azure_poc_ptoal
    storage_account_name: ptoalpoc
    operating_system: other
    publisher: MicrosoftWindowsServer
    offer: WindowsServer
    azureuser: azadmin
    azurepassword: !vault |
          $ANSIBLE_VAULT;1.2;AES256;rhdemo
          35336464363933383136343062663761653365663936393366636233616166653830303932316165
          3161386333396139313938646666656336626632343534660a393463326333383330353739623862
          37363165393735636361383861633133643335316135396661376439353066356364626636666638
          6335613735343534340a633764343532656435353265303534353562343061643334313539663939
          65366133366239363330623261643266303764616465323465376433376436636263
    sku: 2022-datacenter-azure-edition-core
    vm_size: Standard_B1s
    # vm_names: "{{ vm_name.split(',') }}"
    vm_names:
      - "{{ new_vm_hostname }}"

  tasks:
    - name: Resource Group Creation
      ansible.builtin.include_role:
        name: azure_create_resource_group

    - name: Storage Account Creation
      ansible.builtin.include_role:
        name: azure_create_storage_account

    - name: Provision instance Windows
      azure.azcollection.azure_rm_virtualmachine:
        resource_group: "{{ resource_group_name }}"
        name: "{{ item }}"
        storage_account: "{{ storage_account_name }}"
        admin_username: "{{ azureuser }}"
        admin_password: "{{ azurepassword }}"
        vm_size: "{{ vm_size }}"
        os_type: Windows
        managed_disk_type: Standard_LRS
        open_ports:
          - 22
          - 5985
          - 5986
          - 80
          - 443
        image:
          publisher: "{{ publisher }}"
          offer: "{{ offer }}"
          version: "{{ version }}"
          sku: "{{ sku }}"
      register: azure_vm
      loop: "{{ vm_names }}"
      when: publisher == "MicrosoftWindowsServer"

    - name: Create VM script extension to enable HTTPS WinRM listener
      azure.azcollection.azure_rm_virtualmachineextension:
        name: winrm-extension
        resource_group: "{{ resource_group_name }}"
        virtual_machine_name: "{{ item }}"
        publisher: Microsoft.Compute
        virtual_machine_extension_type: CustomScriptExtension
        type_handler_version: "1.9"
        settings: '{"fileUris": ["https://raw.githubusercontent.com/ansible/ansible/devel/examples/scripts/ConfigureRemotingForAnsible.ps1"],"commandToExecute": "powershell
          -ExecutionPolicy Unrestricted -File ConfigureRemotingForAnsible.ps1"}'
        auto_upgrade_minor_version: true
      loop: "{{ vm_names }}"
      when: publisher == "MicrosoftWindowsServer"

    - name: Loop to verify WinRM
      ansible.builtin.include_tasks: enable_winrm_loop_azure.yml
      loop: "{{ vm_names }}"
      when: publisher == "MicrosoftWindowsServer"
