---
- name: Gather Azure Facts from host
  hosts: all
  tasks:
    - name: Use URI module to get info from Azure Metadata service
      ansible.windows.win_uri:
        url: "http://169.254.169.254/metadata/instance?api-version=2019-03-11"
        headers:
          Metadata: true
        return_content: true
      register: azure_metadata_service_info

    - name: Gather VM sizes
      azure.azcollection.azure_rm_virtualmachinesize_info:
        location: "eastus"
      register: vm_size_facts

    - name: Set VM Size info
      set_fact:
        vm_size_info: "{{ vm_size_facts | selectattr('name','==',azure_metadata_service_info.json.compute.vmSize }}"

    - name: Display data
      ansible.builtin.debug:
        var: azure_metadata_service_info.json.compute.location
