---
- name: Apply CIS 2022
  hosts: all
  gather_facts: true
  tasks:
    - name: Optimize Host
      ansible.windows.win_powershell:
        script: |
          $assemblyFilter = "Microsoft.PowerShell."
          $activity = "Native Image Installation"
          # Get the path to the ngen executable dynamically
          $ngenPath = [System.IO.Path]::Combine([Runtime.InteropServices.RuntimeEnvironment]::GetRuntimeDirectory(), "ngen.exe")

          # Check if ngen.exe exists
          if (-Not (Test-Path $ngenPath)) {
              Write-Host "Ngen.exe not found at $ngenPath. Make sure .NET Framework is installed."
              return
          }

          # Get a list of loaded assemblies
          $assemblies = [AppDomain]::CurrentDomain.GetAssemblies()

          # Filter assemblies based on the provided filter
          $filteredAssemblies = $assemblies | Where-Object { $_.FullName -ilike "$assemblyFilter*" }

          if ($filteredAssemblies.Count -eq 0) {
              Write-Host "No matching assemblies found for optimization."
              return
          }

          foreach ($assembly in $filteredAssemblies) {
              # Get the name of the assembly
              $name = [System.IO.Path]::GetFileName($assembly.Location)

              # Display progress
              Write-Progress -Activity $activity -Status "Optimizing $name"

              # Use Ngen to install the assembly
              Start-Process -FilePath $ngenPath -ArgumentList "install `"$($assembly.Location)`"" -Wait -WindowStyle Hidden
          }

          Write-Host "Optimization complete."

    - name: Include Lockdown role
      ansible.builtin.include_role:
        name: Windows-2022-CIS
